In [3]:
import pandas as pd
df = pd.read_csv("loan.csv")
df.head(10)

/tmp/ipykernel_12819/1020525059.py:2: DtypeWarning: Columns (0: desc, 1: verification_status_joint) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("loan.csv")

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,1077501,1296599,5000.0,5000.0,4975.0,36 months,10.65,162.87,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1077430,1314167,2500.0,2500.0,2500.0,60 months,15.27,59.83,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1077175,1313524,2400.0,2400.0,2400.0,36 months,15.96,84.33,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1076863,1277178,10000.0,10000.0,10000.0,36 months,13.49,339.31,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1075358,1311748,3000.0,3000.0,3000.0,60 months,12.69,67.79,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1075269,1311441,5000.0,5000.0,5000.0,36 months,7.90,156.46,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1069639,1304742,7000.0,7000.0,7000.0,60 months,15.96,170.08,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1072053,1288686,3000.0,3000.0,3000.0,36 months,18.64,109.43,E,E1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1071795,1306957,5600.0,5600.0,5600.0,60 months,21.28,152.39,F,F2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1071570,1306721,5375.0,5375.0,5350.0,60 months,12.69,121.45,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose',
       'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt',
       'next_pymnt_d', 'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl',
       'inq_last_12m'],
      dtype='object')

In [4]:
df.shape

(887379, 74)

In [5]:
df.verification_status_joint.value_counts()

verification_status_joint
Not Verified       283
Verified           167
Source Verified     61
Name: count, dtype: int64

In [6]:
# 计算'mths_since_last_delinq'列中值为0的元素数量
(df['mths_since_last_delinq'] == 0).sum()

1723

In [7]:
'desc' in df.columns

True

In [8]:
# float64_columns = df.select_dtypes(include=['float64'])

# float64_columns = float64_columns.shape[1]
# print(float64_columns)

In [9]:
df['mths_since_last_delinq'].unique()

array([ nan,  35.,  38.,  61.,   8.,  20.,  18.,  68.,  45.,  48.,  41.,
        40.,  74.,  25.,  53.,  39.,  10.,  26.,  56.,  77.,  28.,  52.,
        24.,  16.,  60.,  54.,  23.,   9.,  11.,  13.,  65.,  19.,  80.,
        22.,  59.,  79.,  44.,  64.,  57.,  14.,  63.,  49.,  15.,  73.,
        70.,  29.,  51.,   5.,  75.,  55.,   2.,  30.,  47.,  33.,  69.,
         4.,  43.,  21.,  27.,  46.,  81.,  78.,  82.,  31.,  76.,  62.,
        72.,  42.,  50.,   3.,  12.,  67.,  36.,  34.,  58.,  17.,  71.,
        66.,  32.,   6.,  37.,   7.,   1.,  83.,  86., 115.,  96., 103.,
       120., 106.,  89., 107.,  85.,  97.,  95.,   0., 110.,  84., 135.,
        88.,  87., 122.,  91., 146., 134., 114.,  99.,  93., 127., 101.,
        94., 102., 129., 113., 139., 131., 156., 143., 109., 119., 149.,
       118., 130., 148., 126.,  90., 141., 116., 100., 152.,  98.,  92.,
       108., 133., 104., 111., 105., 170., 124., 136., 180., 188., 140.,
       151., 159., 121., 123., 157., 112., 154., 171., 142., 125., 117.,
       176., 137.])

In [10]:
df.describe()\
.T.assign(missing = df.apply(lambda x : (1 - x.count() /len(x)))).sort_values(by = 'missing',ascending = False)

,count,mean,std,min,25%,50%,75%,max,missing
dti_joint,509.0,1.831012e+01,7.169233e+00,3.00,1.320000e+01,1.761000e+01,2.265000e+01,4.386000e+01,0.999426
annual_inc_joint,511.0,1.099810e+05,5.273038e+04,17950.00,7.603250e+04,1.017710e+05,1.328000e+05,5.000000e+05,0.999424
il_util,18617.0,7.153532e+01,2.302286e+01,0.00,5.860000e+01,7.490000e+01,8.760000e+01,2.233000e+02,0.979020
mths_since_rcnt_il,20810.0,2.091269e+01,2.720908e+01,0.00,6.000000e+00,1.200000e+01,2.300000e+01,3.630000e+02,0.976549
open_acc_6m,21372.0,1.109021e+00,1.242675e+00,0.00,0.000000e+00,1.000000e+00,2.000000e+00,1.400000e+01,0.975916
open_il_6m,21372.0,2.928832e+00,3.089987e+00,0.00,1.000000e+00,2.000000e+00,4.000000e+00,4.000000e+01,0.975916
open_il_12m,21372.0,7.616508e-01,9.960346e-01,0.00,0.000000e+00,0.000000e+00,1.000000e+00,1.200000e+01,0.975916
open_il_24m,21372.0,1.674574e+00,1.688725e+00,0.00,0.000000e+00,1.000000e+00,2.000000e+00,1.900000e+01,0.975916
total_bal_il,21372.0,3.655281e+04,4.310383e+04,0.00,1.025150e+04,2.468450e+04,4.785800e+04,8.784590e+05,0.975916
inq_last_12m,21372.0,1.977307e+00,2.874067e+00,-4.00,0.000000e+00,2.000000e+00,3.000000e+00,3.200000e+01,0.975916
max_bal_bc,21372.0,5.887980e+03,5.284701e+03,0.00,2.411000e+03,4.483000e+03,7.771500e+03,1.273050e+05,0.975916
open_rv_24m,21372.0,2.975482e+00,2.631886e+00,0.00,1.000000e+00,2.000000e+00,4.000000e+00,4.300000e+01,0.975916
total_cu_tl,21372.0,1.537058e+00,2.723339e+00,0.00,0.000000e+00,0.000000e+00,2.000000e+00,3.500000e+01,0.975916
inq_fi,21372.0,9.439453e-01,1.446872e+00,0.00,0.000000e+00,0.000000e+00,1.000000e+00,1.700000e+01,0.975916
all_util,21372.0,6.083194e+01,2.001325e+01,0.00,4.770000e+01,6.190000e+01,7.520000e+01,1.514000e+02,0.975916
open_rv_12m,21372.0,1.389060e+00,1.520129e+00,0.00,0.000000e+00,1.000000e+00,2.000000e+00,2.200000e+01,0.975916
mths_since_last_record,137053.0,7.011790e+01,2.812791e+01,0.00,5.100000e+01,7.000000e+01,9.200000e+01,1.290000e+02,0.845553
mths_since_last_major_derog,221703.0,4.410484e+01,2.217984e+01,0.00,2.700000e+01,4.400000e+01,6.100000e+01,1.880000e+02,0.750160
mths_since_last_delinq,433067.0,3.406380e+01,2.188494e+01,0.00,1.500000e+01,3.100000e+01,5.000000e+01,1.880000e+02,0.511971
total_rev_hi_lim,817103.0,3.206862e+04,3.749826e+04,0.00,1.390000e+04,2.370000e+04,3.980000e+04,9.999999e+06,0.079195
tot_cur_bal,817103.0,1.394582e+05,1.537500e+05,0.00,2.985300e+04,8.055900e+04,2.082050e+05,8.000078e+06,0.079195
tot_coll_amt,817103.0,2.257026e+02,1.031137e+04,0.00,0.000000e+00,0.000000e+00,0.000000e+00,9.152545e+06,0.079195
revol_util,886877.0,5.506769e+01,2.383434e+01,0.00,3.770000e+01,5.600000e+01,7.360000e+01,8.923000e+02,0.000566
collections_12_mths_ex_med,887234.0,1.437952e-02,1.341908e-01,0.00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+01,0.000163
total_acc,887350.0,2.526803e+01,1.184056e+01,1.00,1.700000e+01,2.400000e+01,3.200000e+01,1.690000e+02,0.000033
delinq_2yrs,887350.0,3.144419e-01,8.622438e-01,0.00,0.000000e+00,0.000000e+00,0.000000e+00,3.900000e+01,0.000033
pub_rec,887350.0,1.953074e-01,5.820907e-01,0.00,0.000000e+00,0.000000e+00,0.000000e+00,8.600000e+01,0.000033
open_acc,887350.0,1.154847e+01,5.317313e+00,0.00,8.000000e+00,1.100000e+01,1.400000e+01,9.000000e+01,0.000033
acc_now_delinq,887350.0,4.991266e-03,7.762534e-02,0.00,0.000000e+00,0.000000e+00,0.000000e+00,1.400000e+01,0.000033
inq_last_6mths,887350.0,6.946233e-01,9.984477e-01,0.00,0.000000e+00,0.000000e+00,1.000000e+00,3.300000e+01,0.000033
annual_inc,887375.0,7.502759e+04,6.469830e+04,0.00,4.500000e+04,6.500000e+04,9.000000e+04,9.500000e+06,0.000005
id,887379.0,3.246513e+07,2.282734e+07,54734.00,9.206643e+06,3.443327e+07,5.490814e+07,6.861706e+07,0.000000
policy_code,887379.0,1.000000e+00,0.000000e+00,1.00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000
out_prncp,887379.0,8.403125e+03,8.493450e+03,0.00,0.000000e+00,6.458290e+03,1.365906e+04,4.937286e+04,0.000000
loan_amnt,887379.0,1.475526e+04,8.435456e+03,500.00,8.000000e+03,1.300000e+04,2.000000e+04,3.500000e+04,0.000000
funded_amnt,887379.0,1.474188e+04,8.429898e+03,500.00,8.000000e+03,1.300000e+04,2.000000e+04,3.500000e+04,0.000000
funded_amnt_inv,887379.0,1.470246e+04,8.442107e+03,0.00,8.000000e+03,1.300000e+04,2.000000e+04,3.500000e+04,0.000000
int_rate,887379.0,1.324674e+01,4.381867e+00,5.32,9.990000e+00,1.299000e+01,1.620000e+01,2.899000e+01,0.000000
installment,887379.0,4.367171e+02,2.441866e+02,15.67,2.607050e+02,3.825500e+02,5.726000e+02,1.445460e+03,0.000000
dti,887379.0,1.815704e+01,1.719063e+01,0.00,1.191000e+01,1.765000e+01,2.395000e+01,9.999000e+03,0.000000
revol_bal,887379.0,1.692079e+04,2.242679e+04,0.00,6.443000e+03,1.187500e+04,2.082900e+04,2.904836e+06,0.000000
out_prncp_inv,887379.0,8.399713e+03,8.489998e+03,0.00,0.000000e+00,6.455810e+03,1.365405e+04,4.937286e+04,0.000000
last_pymnt_amnt,887379.0,2.164146e+03,4.794783e+03,0.00,2.801700e+02,4.627800e+02,8.312450e+02,3.647559e+04,0.000000
total_pymnt,887379.0,7.558827e+03,7.871243e+03,0.00,1.914590e+03,4.894999e+03,1.061681e+04,5.777758e+04,0.000000
total_pymnt_inv,887379.0,7.521160e+03,7.846109e+03,0.00,1.899700e+03,4.862010e+03,1.056569e+04,5.777758e+04,0.000000
total_rec_prncp,887379.0,5.757706e+03,6.625441e+03,0.00,1.200570e+03,3.215320e+03,8.000000e+03,3.500003e+04,0.000000
total_rec_int,887379.0,1.754804e+03,2.095356e+03,0.00,4.414600e+02,1.073280e+03,2.238265e+03,2.420562e+04,0.000000
total_rec_late_fee,887379.0,3.966918e-01,4.087825e+00,0.00,0.000000e+00,0.000000e+00,0.000000e+00,3.586800e+02,0.000000
member_id,887379.0,3.500182e+07,2.411335e+07,70473.00,1.087713e+07,3.709528e+07,5.847135e+07,7.354484e+07,0.000000
collection_recovery_fee,887379.0,4.880757e+00,6.312528e+01,0.00,0.000000e+00,0.000000e+00,0.000000e+00,7.002190e+03,0.000000
recoveries,887379.0,4.591924e+01,4.096939e+02,0.00,0.000000e+00,0.000000e+00,0.000000e+00,3.352027e+04,0.000000

In [11]:
#缺失超过10%的列直接删除
df1=df.dropna(
    axis=1, thresh=int(0.75 * len(df))) 

#查看处理效果
df1.describe().T.assign(
    missing_pct=df1.apply(
        lambda x: (1 - x.count() / len(x)))).sort_values(
            by='missing_pct', ascending=False)

,count,mean,std,min,25%,50%,75%,max,missing_pct
total_rev_hi_lim,817103.0,3.206862e+04,3.749826e+04,0.00,1.390000e+04,2.370000e+04,3.980000e+04,9.999999e+06,0.079195
tot_cur_bal,817103.0,1.394582e+05,1.537500e+05,0.00,2.985300e+04,8.055900e+04,2.082050e+05,8.000078e+06,0.079195
tot_coll_amt,817103.0,2.257026e+02,1.031137e+04,0.00,0.000000e+00,0.000000e+00,0.000000e+00,9.152545e+06,0.079195
revol_util,886877.0,5.506769e+01,2.383434e+01,0.00,3.770000e+01,5.600000e+01,7.360000e+01,8.923000e+02,0.000566
collections_12_mths_ex_med,887234.0,1.437952e-02,1.341908e-01,0.00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+01,0.000163
inq_last_6mths,887350.0,6.946233e-01,9.984477e-01,0.00,0.000000e+00,0.000000e+00,1.000000e+00,3.300000e+01,0.000033
total_acc,887350.0,2.526803e+01,1.184056e+01,1.00,1.700000e+01,2.400000e+01,3.200000e+01,1.690000e+02,0.000033
pub_rec,887350.0,1.953074e-01,5.820907e-01,0.00,0.000000e+00,0.000000e+00,0.000000e+00,8.600000e+01,0.000033
open_acc,887350.0,1.154847e+01,5.317313e+00,0.00,8.000000e+00,1.100000e+01,1.400000e+01,9.000000e+01,0.000033
delinq_2yrs,887350.0,3.144419e-01,8.622438e-01,0.00,0.000000e+00,0.000000e+00,0.000000e+00,3.900000e+01,0.000033
acc_now_delinq,887350.0,4.991266e-03,7.762534e-02,0.00,0.000000e+00,0.000000e+00,0.000000e+00,1.400000e+01,0.000033
annual_inc,887375.0,7.502759e+04,6.469830e+04,0.00,4.500000e+04,6.500000e+04,9.000000e+04,9.500000e+06,0.000005
total_rec_prncp,887379.0,5.757706e+03,6.625441e+03,0.00,1.200570e+03,3.215320e+03,8.000000e+03,3.500003e+04,0.000000
last_pymnt_amnt,887379.0,2.164146e+03,4.794783e+03,0.00,2.801700e+02,4.627800e+02,8.312450e+02,3.647559e+04,0.000000
collection_recovery_fee,887379.0,4.880757e+00,6.312528e+01,0.00,0.000000e+00,0.000000e+00,0.000000e+00,7.002190e+03,0.000000
policy_code,887379.0,1.000000e+00,0.000000e+00,1.00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000
recoveries,887379.0,4.591924e+01,4.096939e+02,0.00,0.000000e+00,0.000000e+00,0.000000e+00,3.352027e+04,0.000000
total_rec_late_fee,887379.0,3.966918e-01,4.087825e+00,0.00,0.000000e+00,0.000000e+00,0.000000e+00,3.586800e+02,0.000000
total_rec_int,887379.0,1.754804e+03,2.095356e+03,0.00,4.414600e+02,1.073280e+03,2.238265e+03,2.420562e+04,0.000000
id,887379.0,3.246513e+07,2.282734e+07,54734.00,9.206643e+06,3.443327e+07,5.490814e+07,6.861706e+07,0.000000
total_pymnt_inv,887379.0,7.521160e+03,7.846109e+03,0.00,1.899700e+03,4.862010e+03,1.056569e+04,5.777758e+04,0.000000
total_pymnt,887379.0,7.558827e+03,7.871243e+03,0.00,1.914590e+03,4.894999e+03,1.061681e+04,5.777758e+04,0.000000
out_prncp_inv,887379.0,8.399713e+03,8.489998e+03,0.00,0.000000e+00,6.455810e+03,1.365405e+04,4.937286e+04,0.000000
member_id,887379.0,3.500182e+07,2.411335e+07,70473.00,1.087713e+07,3.709528e+07,5.847135e+07,7.354484e+07,0.000000
revol_bal,887379.0,1.692079e+04,2.242679e+04,0.00,6.443000e+03,1.187500e+04,2.082900e+04,2.904836e+06,0.000000
dti,887379.0,1.815704e+01,1.719063e+01,0.00,1.191000e+01,1.765000e+01,2.395000e+01,9.999000e+03,0.000000
installment,887379.0,4.367171e+02,2.441866e+02,15.67,2.607050e+02,3.825500e+02,5.726000e+02,1.445460e+03,0.000000
int_rate,887379.0,1.324674e+01,4.381867e+00,5.32,9.990000e+00,1.299000e+01,1.620000e+01,2.899000e+01,0.000000
funded_amnt_inv,887379.0,1.470246e+04,8.442107e+03,0.00,8.000000e+03,1.300000e+04,2.000000e+04,3.500000e+04,0.000000
funded_amnt,887379.0,1.474188e+04,8.429898e+03,500.00,8.000000e+03,1.300000e+04,2.000000e+04,3.500000e+04,0.000000
loan_amnt,887379.0,1.475526e+04,8.435456e+03,500.00,8.000000e+03,1.300000e+04,2.000000e+04,3.500000e+04,0.000000
out_prncp,887379.0,8.403125e+03,8.493450e+03,0.00,0.000000e+00,6.458290e+03,1.365906e+04,4.937286e+04,0.000000

In [12]:
(df['annual_inc'] == 0).sum()

2

In [13]:
set(df.columns) - set(df1.columns)

{'all_util',
 'annual_inc_joint',
 'desc',
 'dti_joint',
 'il_util',
 'inq_fi',
 'inq_last_12m',
 'max_bal_bc',
 'mths_since_last_delinq',
 'mths_since_last_major_derog',
 'mths_since_last_record',
 'mths_since_rcnt_il',
 'next_pymnt_d',
 'open_acc_6m',
 'open_il_12m',
 'open_il_24m',
 'open_il_6m',
 'open_rv_12m',
 'open_rv_24m',
 'total_bal_il',
 'total_cu_tl',
 'verification_status_joint'}

In [14]:
df1.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim
0,1077501,1296599,5000.0,5000.0,4975.0,36 months,10.65,162.87,B,B2,...,Jan-2015,171.62,Jan-2016,0.0,1.0,INDIVIDUAL,0.0,NaN,NaN,NaN
1,1077430,1314167,2500.0,2500.0,2500.0,60 months,15.27,59.83,C,C4,...,Apr-2013,119.66,Sep-2013,0.0,1.0,INDIVIDUAL,0.0,NaN,NaN,NaN
2,1077175,1313524,2400.0,2400.0,2400.0,36 months,15.96,84.33,C,C5,...,Jun-2014,649.91,Jan-2016,0.0,1.0,INDIVIDUAL,0.0,NaN,NaN,NaN
3,1076863,1277178,10000.0,10000.0,10000.0,36 months,13.49,339.31,C,C1,...,Jan-2015,357.48,Jan-2015,0.0,1.0,INDIVIDUAL,0.0,NaN,NaN,NaN
4,1075358,1311748,3000.0,3000.0,3000.0,60 months,12.69,67.79,B,B5,...,Jan-2016,67.79,Jan-2016,0.0,1.0,INDIVIDUAL,0.0,NaN,NaN,NaN

In [ ]:
# 【特征选择步骤已移至《2 数据编码、降维》notebook】
# 以下操作（删除高基数列、检查不平衡列、手动删除冗余列）属于特征工程范畴，
# 在特征工程阶段统一处理。本 notebook 只完成数据质量修复（缺失值处理）。

In [ ]:
# 观察缺失值
df1.isnull().sum()

In [ ]:
#缺失值处理

# total_rev_hi_lim：总周转高信用/信用额度。以mean填充
# tot_cur_bal：所有帐户的当前总余额。 以0填充
# tot_coll_amt：欠款总额。以0填充
# revol_util：循环利用率，或借款人相对于所有可用循环信贷使用的信贷额度。以mean填充
# collections_12_mths_ex_med:除医疗账单外12个月的欠款数量。以0填充
# inq_last_6mths：过去6个月的征信查询数目（不包括汽车及按揭查询）。以0填充
# acc_now_delinq: 借款人现在欠款的账户数量。以0填充
# pub_rec: 贬损公共记录的数量。以0填充
# open_acc；借款人信用档案中的未结信用额度。以mean填充
# total_acc：借款人信用档案中当前信用额度的总数。以mean填充
# delinq_2yrs：过去两年借款人信用档案中逾期30天以上的拖欠次数。以0填充
# annual_inc：借款人在注册期间自行报告的年收入。以mean填充。
# emp_length：工作年限。以0填充

cols_fill_with_zero = [
    'tot_cur_bal', 'tot_coll_amt',
    'collections_12_mths_ex_med', 'acc_now_delinq',
    'pub_rec', 'delinq_2yrs','emp_length'
]
cols_fill_with_mean = ['total_rev_hi_lim', 'revol_util', 'annual_inc']

df2 = df1
for col in cols_fill_with_zero:
    df2[col] = df1[col].fillna(0)

for col in cols_fill_with_mean:
    mean_of_col = df1[col].mean()
    df2[col] = df1[col].fillna(mean_of_col)

print(df2.shape)
df2.head()

In [ ]:
df2 = df2.dropna(axis=0)  # 剔除剩余行里有空值的行

df2.shape

In [ ]:
# 将数据框写入CSV文件
df2.to_csv('loan_filtered.csv', index=False)